spring:
  application:
    name: gearbox

  datasource:
    url: jdbc:postgresql://gearbox-db.c5wocmau8vx7.eu-central-1.rds.amazonaws.com:5432/gearbox
    username: developer
    password: comsystoreply

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded

  servlet:
    multipart:
      max-file-size: 2MB

jwt:
  key: ${JWT_KEY}
  accessTokenExpiration: 86_400_000
  refreshTokenExpiration: 604_800_000

firebase:
  storage-bucket: gearbox-c768b.appspot.com

server:
  port: 8080